export const ApiRoutes = {
  API_HOSTNAME: "http://192.168.1.18:8000",
  LOGIN: "login",
  CHECKEMAIL: "check-email",
  CHECKMOBILE: "check-mobile",
  REGISTER: "register",
  GETATTRIBUTEBYID: "get-attributebyid",
  INSERTVIDEO: "insert-video",
  GETVIDEOS: "get-videos",
  UPDATEVIDEO: "update-video",
  INSERTQUESTION: "insert-question",
  UPDATEQUESTION: "update-question",
  GETQUESTIONS: "get-questions",
  GETOPTIONSBYID: "get-option",
  DELETEOPTION: "delete-option",
  UPDATEVIDEOPERCENTAGE: "update-videopercentage",
  INSERTVIDEOPERCENTAGE: "insert-videopercentage",
  GETVIDEOSWITHPERCENTAGE: "get-videoswithpercentage",
  GETQUESTIONSFORQUIZ: "get-questionforquiz",
  GETOPTIONSFORQUIZBYID: "get-optionforquiz",
  INSERTQUIZ: "insert-quiz",
  GETQUIZRESULT: "get-quizresult",
};
